baseURL = "https://aghribi.github.io/acc-ml-living-review/"
languageCode = "en-us"
title = "The AI/ML for particle accelerators living review"

[params]
  github = "https://github.com/aghribi/acc-ml-living-review"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url  = "https://github.com/aghribi/acc-ml-living-review"

[taxonomies]
  category = "categories"
  tag = "tags"
  venue = "venues"
  year = "years"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown

# Menu configuration
[menu]
  [[menu.main]]
    name = "Access the Living Review"
    url = "/papers/"
    weight = 1
  
  [[menu.main]]
    name = "Submit Paper"
    url = "/submit/"
    weight = 2
  
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 3
  
  [[menu.main]]
    name = "Cite Us"
    url = "/cite/"
    weight = 4

[build]
  writeStats = true