name: Update Living Review Data

env:
  SPRINGER_API_KEY: ${{ secrets.SPRINGER_API_KEY }}
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # every night at 3am UTC

permissions:
  contents: write   # allow commits with GITHUB_TOKEN

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      UPDATE_INTERVAL_HOURS: 24   # hours between updates
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .   # optional, if you want your package available

      - name: Run pipeline
        run: python -m living_review.cli --days 30 --sources all

      - name: Commit updated data
        run: |
          git config user.name "livingreview-bot"
          git config user.email "bot@example.com"
          git add site/data/*.json site/static/downloads/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Update living review data"
            git push
          else
            echo "No changes to commit."
          fi
